// Desktop (1440) screens, built from the app's real seed data.
import { doc, esc, icon, img, P, brand, brandMark, themeToggle, likeBtn, stars, rating, field, input, select, avatar, fmtNum, fmtNewsDate, newsSeeds, popularPlaces, seedTrips, catalog, byId, boardFor, categoryLabels, newsCategoryLabels, regionCover, leg, transport, orderPlaces, priceLabel } from './lib.mjs';
import { boardScreenDesktop, schedule } from './board.mjs';
import { appNav, fab, tripCard, popularCard, newsCard, heroPins } from './cards.mjs';
import { tripPost } from './system.mjs';

const kl = boardFor('seed-kl-city-lights');
const penang = boardFor('seed-penang-heritage');
const petronas = kl.placeById.get('seed-kl-petronas-towers');

const pageCss = `
.feat .fi{transition:border-radius .28s var(--ease),background .2s ease,color .2s ease}
.feat:hover .fi{border-radius:999px;background:var(--coral-soft);color:var(--coral-deep)}
.h-page{font-size:44px}
`;
const W = 1440;
const screen = (body, h, opts = {}) => doc(body, { width: W, height: h, css: pageCss, ...opts });
const overlay = (base, modal, h = 900) => `<div style="position: relative; height: ${h}px; overflow: hidden;">${base}<div class="scrim"></div>${modal}</div>`;

// ---------- Landing ----------
const miniCard = (c) => `<div style="border-radius: 18px; overflow: hidden; background: var(--raised); border: 1px solid var(--line); box-shadow: var(--shadow-2);"><div class="cover" style="height: 108px;"><img src="${img(c.image)}" alt=""></div><div style="padding: 10px 12px 12px;"><p class="trunc" style="font: 650 13.5px/1.3 var(--body);">${esc(c.name)}</p><p class="row muted" style="justify-content: space-between; font-size: 11.5px; margin-top: 3px;"><span>${esc(c.city)}</span>${rating(c.rating, 11)}</p></div></div>`;
const miniBoard = () => {
  const [batu, tower, alor] = ['kl-batu-caves', 'kl-petronas-towers', 'kl-jalan-alor'].map((id) => byId.get(id));
  const l1 = leg(batu, tower, 'train'); const l2 = leg(tower, alor, 'walk');
  const pill = (x, mode, dur) => `<span class="epill" style="left: ${x}px; top: 42px;">${icon(transport[mode].icon, 13)}${transport[mode].label}<span class="dur">· ${dur}</span></span>`;
  return `<div class="card dots-bg" style="position: relative; padding: 24px; border-radius: 28px; box-shadow: var(--shadow-3);"><div class="row" style="justify-content: space-between;"><span class="chip chip-raised" style="box-shadow: var(--shadow-1);">KL City Lights · board</span><span class="faint" style="font-size: 12px; font-weight: 600;">3 places · 2 routes</span></div><div style="position: relative; height: 84px; margin-top: 12px;">${heroPins({ w: 592, h: 84, pts: [[93, 64], [296, 38], [499, 64]] })}${pill(194, 'train', l1.duration)}${pill(398, 'walk', l2.duration)}</div><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; margin-top: 4px;">${[batu, tower, alor].map(miniCard).join('')}</div></div>`;
};

export const landing = () => {
  const features = [
    ['grid', 'Plan on a visual board', 'Every trip is a canvas. Drag places on, arrange them how you think, and see the whole plan at a glance.'],
    ['route', 'Connect the dots', 'Draw a route between two places and pick how you get there — walk, train, bus or car — with a rough time estimate.'],
    ['pin', `${catalog.length} Malaysian places, ready to drag`, 'Landmarks, hawker streets, beaches, tea hills and cafés across all 13 regions, from KL and Penang to Sabah and Sarawak.'],
    ['compass', 'Place intel in one tap', 'Tap any card for a map, opening hours, ratings and reviews before you commit it to the plan.'],
    ['newspaper', 'News from the ground', 'New cafés, reopened beach clubs and weekend markets, written short enough to read on the train.'],
    ['bookmark', 'Collections for later', 'Save destinations you have visited or want to go, and turn the best ones into boards.'],
  ];
  const demos = seedTrips.map((t) => `<div class="row" style="gap: 14px; padding: 12px; border-radius: 18px; background: rgb(255 255 255 / 0.06);"><span class="cover" style="width: 64px; height: 44px; border-radius: 10px; flex: none;"><img src="${regionCover(t.region)}" alt=""></span><div style="min-width: 0;"><p style="font: 650 14.5px/1.3 var(--body);">${esc(t.destination)}</p><p style="font-size: 12.5px; color: rgb(237 242 251 / 0.7); margin-top: 2px;">${esc(t.description)}</p></div></div>`).join('');
  return screen(`<header class="container row" style="justify-content: space-between; height: 88px;">${brand(34)}<div class="row" style="gap: 8px;">${themeToggle()}<span class="btn btn-ghost">Sign in</span><span class="btn btn-primary">Get started</span></div></header>
<section class="container" style="display: grid; grid-template-columns: minmax(0, 1fr) 640px; gap: 64px; align-items: center; padding: 48px 0 104px;">
<div><span class="chip chip-raised" style="height: 30px; padding: 0 12px; font-size: 11px; box-shadow: var(--shadow-1);">${icon('pin', 12, '', ' style="color: var(--coral-deep);"')}Made for trips across Malaysia</span>
<h1 style="font: 800 72px/1.02 var(--display); letter-spacing: -0.04em; margin-top: 26px;">Plan your trip like a <span style="position: relative; display: inline-block; color: var(--primary-ink);">flow<svg class="squiggle" viewBox="0 0 188 20" preserveAspectRatio="none" aria-hidden="true" style="position: absolute; left: -2%; bottom: -12px; width: 104%; height: 18px; overflow: visible;"><path d="${P.LINE}" style="fill: none; stroke: var(--coral); stroke-width: 5; stroke-linecap: round;"></path></svg></span>, not a spreadsheet.</h1>
<p class="muted" style="font-size: 18px; line-height: 1.6; margin-top: 30px; max-width: 520px;">Drag places onto a board, connect them into a route, choose how you travel between stops, and keep the whole plan on one calm canvas.</p>
<div class="row" style="gap: 12px; margin-top: 36px;"><span class="btn btn-primary btn-lg">Start a board${icon('arrow-right', 18)}</span><span class="btn btn-outline btn-lg">Explore the demo</span></div>
<p class="faint" style="margin-top: 18px; font-size: 13px;">The demo opens three sample boards — no account needed.</p></div>
${miniBoard()}
</section>
<section style="background: var(--raised); border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); padding: 88px 0;"><div class="container"><div style="max-width: 640px;"><h2 style="font-size: 40px;">Everything on the board</h2><p class="muted" style="font-size: 16px; margin-top: 12px;">Explore three sample boards without an account, then sign in when you want to keep your own.</p></div>
<div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 20px; margin-top: 40px;">${features.map(([ic, title, text]) => `<article class="feat" style="padding: 28px; border-radius: 24px; background: var(--surface); border: 1px solid var(--line);"><span class="fi" style="display: flex; width: 48px; height: 48px; border-radius: 14px; align-items: center; justify-content: center; background: var(--raised); color: var(--primary-ink); border: 1px solid var(--line);">${icon(ic, 22)}</span><h3 style="font-size: 20px; margin-top: 22px;">${esc(title)}</h3><p class="muted" style="font-size: 14.5px; line-height: 1.6; margin-top: 8px;">${esc(text)}</p></article>`).join('')}</div></div></section>
<section class="container" style="display: grid; grid-template-columns: minmax(0, 1fr) 560px; gap: 72px; align-items: center; padding: 96px 0;"><div><h2 style="font-size: 40px;">A planning board, not a booking site</h2><p class="muted" style="font-size: 16px; line-height: 1.65; margin-top: 16px; max-width: 520px;">TravelPlanner helps you decide where to go and how to get between places. Bookings stay with the airlines, hotels and ticket counters. Your boards stay private to your account until you share them.</p><div class="row" style="gap: 12px; margin-top: 32px;"><span class="btn btn-primary btn-lg">Create account${icon('arrow-right', 18)}</span><span class="btn btn-ghost btn-lg">Sign in</span></div></div>
<div style="border-radius: 28px; padding: 28px; background: #1B2559; color: #EDF2FB; box-shadow: var(--shadow-3);"><div class="row" style="gap: 14px; margin-bottom: 20px;">${brandMark(40)}<div><p style="font: 700 17px/1.3 var(--display);">Three demo boards included</p><p style="font-size: 13px; color: rgb(237 242 251 / 0.7);">Different vibes, all drag-and-drop.</p></div></div><div style="display: flex; flex-direction: column; gap: 10px;">${demos}</div></div></section>
<footer class="container row" style="justify-content: space-between; padding: 32px 0 40px; border-top: 1px solid var(--line);">${brand(26, true, 15)}<p class="faint" style="font-size: 12.5px; font-weight: 600;">© 2026 TravelPlanner · Plan the flow, enjoy the trip.</p></footer>`, 2060);
};

// ---------- Auth ----------
const authShell = (card) => `<div class="dots-bg" style="position: relative; width: ${W}px; height: 900px; display: flex; align-items: center; justify-content: center;"><div style="position: absolute; left: 40px; top: 28px;">${brand(32)}</div><div style="position: absolute; right: 40px; top: 28px;">${themeToggle()}</div>${card}</div>`;
export const signIn = () => screen(authShell(`<section class="card" style="width: 440px; padding: 40px; border-radius: 28px; box-shadow: var(--shadow-3);"><h1 style="font-size: 34px;">Sign in</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">Pick up your boards where you left them.</p><div style="display: flex; flex-direction: column; gap: 16px; margin-top: 28px;">${field('Email', input('demo@travelplanner.local', { lead: icon('mail', 16) }))}${field('Password', input('•••••••••••••••••', { lead: icon('lock', 16), trail: icon('eye', 16) }))}</div><span class="btn btn-primary btn-lg btn-block" style="margin-top: 24px;">Sign in</span><div class="alert alert-info" style="margin-top: 14px; font-size: 12.5px;">${icon('user', 15)}<span>Demo login: <b>demo@travelplanner.local</b> / TravelPlanner123!</span></div><div class="row" style="gap: 12px; margin: 22px 0 6px;"><span style="flex: 1; height: 1px; background: var(--line);"></span><span class="faint" style="font-size: 12px; font-weight: 600;">or</span><span style="flex: 1; height: 1px; background: var(--line);"></span></div><span class="btn btn-ghost btn-block" style="color: var(--primary-ink);">Explore the demo boards instead</span><p class="muted" style="text-align: center; margin-top: 16px; font-size: 13.5px;">New here? <a href="#">Create an account</a></p></section>`), 900);
export const signUp = () => screen(authShell(`<section class="card" style="width: 440px; padding: 40px; border-radius: 28px; box-shadow: var(--shadow-3);"><h1 style="font-size: 34px;">Create your account</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">Your account lives on this machine in the local prototype.</p><div style="display: flex; flex-direction: column; gap: 16px; margin-top: 28px;">${field('Full name', input('Aina Rahman', { cls: 'focus' }))}${field('Email', input('you@example.com', { ph: true, lead: icon('mail', 16) }), { req: true })}${field('Password', input('At least 8 characters', { ph: true, lead: icon('lock', 16), trail: icon('eye', 16) }), { req: true, help: 'Use 8 or more characters.' })}</div><span class="btn btn-primary btn-lg btn-block" style="margin-top: 24px;">Create account</span><div class="row" style="gap: 12px; margin: 22px 0 6px;"><span style="flex: 1; height: 1px; background: var(--line);"></span><span class="faint" style="font-size: 12px; font-weight: 600;">or</span><span style="flex: 1; height: 1px; background: var(--line);"></span></div><span class="btn btn-ghost btn-block" style="color: var(--primary-ink);">Explore the demo boards instead</span><p class="muted" style="text-align: center; margin-top: 16px; font-size: 13.5px;">Already have an account? <a href="#">Sign in</a></p></section>`), 900);

// ---------- Dashboard ----------
const popularBanner = () => `<section style="position: relative; border-radius: 28px; padding: 32px 0 32px 32px; background: #1B2559; color: #EDF2FB; overflow: hidden;"><div style="position: absolute; inset: 0; background-image: radial-gradient(rgb(171 196 255 / 0.14) 1.3px, transparent 1.5px); background-size: 22px 22px;"></div><div class="row" style="position: relative; justify-content: space-between; align-items: flex-end; gap: 32px; padding-right: 32px;"><div><span class="chip" style="height: 28px; padding: 0 12px; background: rgb(255 255 255 / 0.1); color: #EDF2FB;">${icon('sparkles', 13)}Popular right now in Malaysia</span><h2 style="font-size: 32px; margin-top: 14px; color: #FFFFFF;">Places travellers are adding to their boards</h2></div><p style="max-width: 340px; font-size: 14px; line-height: 1.55; color: rgb(237 242 251 / 0.78);">Tap a place for reviews and a map, or start a trip in that region and drag it onto your board.</p></div><div style="position: relative; display: flex; gap: 16px; margin-top: 26px;">${popularPlaces.slice(0, 6).map((c) => popularCard(c)).join('')}</div><span class="btn btn-icon" style="position: absolute; right: 24px; bottom: 140px; background: #FFFFFF; color: #1B2559; box-shadow: var(--shadow-2);" aria-label="More popular places">${icon('chevron-right', 18)}</span></section>`;
const statTile = (label, value, note, dot) => `<div class="card" style="padding: 20px 22px; border-radius: 20px; display: flex; align-items: center; gap: 18px;"><span style="font: 800 40px/1 var(--display); letter-spacing: -0.03em; min-width: 36px;">${value}</span><div><p class="row" style="gap: 8px; font: 700 13.5px/1.2 var(--body);"><span style="width: 8px; height: 8px; border-radius: 99px; background: ${dot};"></span>${label}</p><p class="muted" style="font-size: 12.5px; margin-top: 4px;">${note}</p></div></div>`;
const dashboardBody = () => `${appNav('trips')}<main class="container" style="padding: 8px 0 120px;">${popularBanner()}<div class="row" style="justify-content: space-between; align-items: flex-end; margin-top: 52px;"><div><h1 class="h-page">Hi Demo, your boards</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">Explore three sample plans. Everything you change is saved in this browser.</p></div>${input('Search trips or regions', { ph: true, lead: icon('search', 16), style: 'width: 320px; border-radius: 999px; background: var(--raised);' })}</div><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; margin-top: 28px;">${statTile('Upcoming', 3, 'Next: Penang Heritage &amp; Street Food · Oct 9', 'var(--primary)')}${statTile('Active', 0, 'Nothing on the go right now', 'var(--pos)')}${statTile('Past', 0, 'Finished trips land here', 'var(--faint)')}</div><div style="display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 24px; margin-top: 36px;">${seedTrips.map((t) => tripCard(t, { w: 290 })).join('')}</div></main>`;
export const dashboard = () => screen(`${dashboardBody()}${fab()}`, 1340);

export const dashboardNewTrip = () => screen(overlay(dashboardBody(), `<div class="modal" style="left: ${(W - 480) / 2}px; top: 96px; width: 480px;"><div class="cover" style="position: relative; height: 120px;"><img src="${regionCover('Ipoh')}" alt=""><span class="btn btn-icon btn-sm" style="position: absolute; right: 14px; top: 14px; background: rgb(14 20 48 / 0.55); color: #F5F8FE;" aria-label="Close">${icon('x', 16)}</span></div><div style="padding: 22px 24px 0;"><h2 style="font-size: 24px;">New Trip</h2><p class="muted" style="font-size: 13.5px; margin-top: 4px;">The cover follows the region you pick.</p></div><div class="modal-body">${field('Trip name', input('Ipoh long weekend'), { req: true })}${field('Region', select('Ipoh'))}<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px;">${field('Start date', input('Dec 12, 2026', { trail: icon('calendar', 16) }), { req: true })}${field('End date', input('Dec 14, 2026', { trail: icon('calendar', 16) }), { req: true })}</div>${field('Description (optional)', `<div class="input area ph" style="min-height: 84px;">What’s the vibe of this trip?</div>`)}</div><div class="modal-foot"><span class="btn btn-ghost">Cancel</span><span class="btn btn-primary">Create trip${icon('arrow-right', 16)}</span></div></div>${fab('Close', 'position: absolute; right: 32px; bottom: 32px;').replace('<input type="checkbox"', '<input type="checkbox" checked')}`));

// ---------- Collections ----------
const collections = [
  { destination: 'Cameron Highlands', status: 'want_to_go', notes: 'Tea terraces and cold mornings after KL.' },
  { destination: 'Malacca', status: 'visited', notes: 'Jonker night market was the highlight.' },
];
const collectionItem = (item) => `<article style="display: flex; gap: 16px; padding: 14px; border-radius: 20px; background: var(--surface); border: 1px solid var(--line);"><span class="cover" style="width: 104px; height: 74px; border-radius: 14px; flex: none;"><img src="${regionCover(item.destination)}" alt=""></span><div style="flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 10px;"><div class="row" style="justify-content: space-between; gap: 12px;"><div><h4 style="font-size: 17px;">${esc(item.destination)}</h4><p class="muted" style="font-size: 13.5px; margin-top: 4px;">${esc(item.notes)}</p></div><div class="row" style="gap: 2px;"><span class="btn btn-ghost btn-icon btn-sm" aria-label="Edit ${esc(item.destination)}">${icon('pencil', 15)}</span><span class="btn btn-ghost btn-icon btn-sm" aria-label="Delete ${esc(item.destination)}">${icon('trash', 15)}</span></div></div><div class="row" style="gap: 8px;"><span class="btn btn-primary btn-sm">${icon('plus', 14)}Plan trip</span>${item.status === 'want_to_go' ? `<span class="btn btn-outline btn-sm">${icon('check', 14)}Mark visited</span>` : `<span class="btn btn-outline btn-sm">${icon('undo', 14)}Want to go</span>`}</div></div></article>`;
const collectionCol = (label, status) => {
  const items = collections.filter((c) => c.status === status);
  return `<div class="card" style="padding: 20px; display: flex; flex-direction: column; gap: 12px;"><div class="row" style="justify-content: space-between;"><h3 class="eyebrow" style="color: var(--muted);">${label}</h3><span class="chip chip-mist">${items.length}</span></div>${items.map(collectionItem).join('')}</div>`;
};
export const collectionsScreen = () => screen(`${appNav('collections')}<main class="container" style="padding: 24px 0 120px;"><h1 class="h-page">Collections</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">Save places you have visited or want to turn into future boards.</p><div class="card" style="margin-top: 32px; padding: 20px; display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1.3fr) 180px auto; gap: 14px; align-items: end;">${field('Destination', input('e.g. Ipoh', { ph: true }), { req: true })}${field('Notes', input('Why it’s on the list', { ph: true }))}${field('Status', select('Want to go'))}<span class="btn btn-primary" style="height: 44px;">${icon('plus', 16)}Save</span></div><div class="row" style="justify-content: space-between; margin-top: 36px;"><h2 style="font-size: 24px;">Saved destinations</h2><span class="eyebrow">2 saved</span></div><div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; margin-top: 16px;">${collectionCol('Want to go', 'want_to_go')}${collectionCol('Visited', 'visited')}</div></main>${fab()}`, 960);

// ---------- Profile ----------
export const profileScreen = () => screen(`${appNav('profile')}<main style="width: 960px; margin: 0 auto; padding: 24px 0 96px;"><h1 class="h-page">Your profile</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">Changes stay in this browser while you explore the demo.</p><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; margin-top: 28px;">${[['Boards', 3, 'grid'], ['Complete plans', 1, 'circle-check'], ['Stories liked', 0, 'heart']].map(([label, value, ic]) => `<div class="card" style="padding: 20px 22px; border-radius: 20px;"><p class="eyebrow row" style="gap: 8px;">${icon(ic, 14)}${label}</p><p style="font: 800 36px/1 var(--display); margin-top: 12px;">${value}</p></div>`).join('')}</div><div class="card" style="margin-top: 24px; padding: 32px; display: grid; grid-template-columns: 220px minmax(0, 1fr); gap: 40px;"><div style="display: flex; flex-direction: column; align-items: center; gap: 14px; text-align: center;">${avatar('Demo Traveler', 144)}<span class="btn btn-outline btn-sm">${icon('camera', 15)}Upload photo</span><p class="faint" style="font-size: 12px;">Square crop, resized to 256 px.</p></div><div style="display: flex; flex-direction: column; gap: 18px;"><div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px;">${field('Display name', input('Demo Traveler'), { req: true })}${field('Email', input('demo@example.com', { cls: 'readonly' }), { help: 'Used to sign in · can’t be changed here' })}${field('Gender', select('Prefer not to say'))}${field('Date of birth', input('Not set', { ph: true, trail: icon('calendar', 16) }))}${field('Home city', input('Kuala Lumpur'))}${field('Country', input('Malaysia'))}</div>${field('Short bio', `<div class="input area ph">Slow mornings, street food, one museum per trip.</div>`, { help: '0 / 280' })}<div class="row" style="justify-content: flex-end;"><span class="btn btn-primary">Save profile</span></div></div></div></main>`, 1120);

// ---------- Board screens ----------
export const boardEdit = () => screen(boardScreenDesktop(kl, { mode: 'edit', selectedId: 'seed-kl-petronas-towers', openEdgeId: 'seed-kl-link-3', z: 0.8, tx: 36, ty: 250 }), 900);
export const boardView = () => screen(boardScreenDesktop(penang, { mode: 'view', z: 0.62, tx: 40, ty: 236 }), 900);
export const boardDark = () => screen(boardScreenDesktop(kl, { mode: 'edit', dark: true, dayFilter: 2, z: 0.8, tx: 36, ty: 250 }), 900, { dark: true });

const mapArt = (w, h) => `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" aria-hidden="true" style="display: block;"><rect width="${w}" height="${h}" style="fill: #E9EFFA;"></rect><path d="M0 ${h * 0.74} C${w * 0.3} ${h * 0.62} ${w * 0.55} ${h * 0.96} ${w} ${h * 0.8} L${w} ${h} L0 ${h} Z" style="fill: #D3E1FB;"></path><rect x="${w * 0.56}" y="${h * 0.14}" width="${w * 0.24}" height="${h * 0.38}" rx="12" style="fill: #DCEBDF;"></rect><g style="fill: none; stroke: #FFFFFF; stroke-linecap: round;"><path d="M0 ${h * 0.35} L${w} ${h * 0.28}" style="stroke-width: 7;"></path><path d="M${w * 0.32} 0 L${w * 0.4} ${h}" style="stroke-width: 7;"></path><path d="M${w * 0.7} 0 C${w * 0.66} ${h * 0.4} ${w * 0.78} ${h * 0.6} ${w * 0.74} ${h}" style="stroke-width: 5;"></path><path d="M0 ${h * 0.58} L${w * 0.5} ${h * 0.55}" style="stroke-width: 4;"></path><path d="M${w * 0.12} 0 L${w * 0.2} ${h * 0.7}" style="stroke-width: 3;"></path><path d="M${w * 0.84} ${h * 0.1} L${w} ${h * 0.46}" style="stroke-width: 3;"></path></g><g transform="translate(${w / 2 - 18} ${h / 2 - 40}) scale(1.5)"><path d="${P.PIN}" style="fill: var(--coral); fill-rule: evenodd; stroke: #FFFFFF; stroke-width: 1.2;"></path></g><text x="${w - 8}" y="${h - 8}" text-anchor="end" style="font: 500 9px var(--body); fill: #5F6994;">© OpenStreetMap contributors</text></svg>`;
const fmtReviewDate = (v) => new Intl.DateTimeFormat('en-GB', { month: 'short', year: 'numeric' }).format(new Date(`${v}T00:00:00`));

export const placeIntel = () => {
  const c = petronas.c;
  const reviews = c.reviews.map((r) => `<li style="padding: 14px 16px; border-radius: 16px; background: var(--surface); border: 1px solid var(--line);"><div class="row" style="justify-content: space-between; gap: 12px;"><span class="row" style="gap: 10px; font: 650 13.5px/1 var(--body);">${avatar(r.author, 28)}${esc(r.author)}</span><span class="row faint" style="gap: 8px; font-size: 12px;">${stars(r.rating, 12)}${fmtReviewDate(r.date)}</span></div><p class="muted" style="font-size: 13.5px; line-height: 1.55; margin-top: 8px;">${esc(r.text)}</p></li>`).join('');
  const modal = `<section class="modal" role="dialog" aria-labelledby="pi-title" style="left: 180px; top: 48px; width: 1080px; height: 804px; display: grid; grid-template-columns: 460px minmax(0, 1fr);"><div style="display: flex; flex-direction: column; border-right: 1px solid var(--line); min-width: 0;"><div class="cover" style="position: relative; height: 288px; flex: none;"><img src="${img(c.image)}" alt="${esc(c.name)}"><span class="chip chip-raised" style="position: absolute; left: 18px; top: 18px;">${categoryLabels[c.category]}</span></div><div style="position: relative; flex: 1; overflow: hidden; border-top: 1px solid var(--line);">${mapArt(460, 516)}<span class="btn btn-sm" style="position: absolute; right: 14px; top: 14px; background: var(--raised); box-shadow: var(--shadow-1);">${icon('maximize', 14)}Expand map</span></div></div><div style="position: relative; display: flex; flex-direction: column; min-width: 0;"><span class="btn btn-soft btn-icon" style="position: absolute; right: 18px; top: 18px;" aria-label="Close place details">${icon('x', 18)}</span><div style="flex: 1; overflow: hidden; padding: 32px 36px 0;"><p class="eyebrow">Place intel · ${esc(c.region)}</p><h2 id="pi-title" style="font-size: 38px; margin-top: 10px;">${esc(c.name)}</h2><p class="muted" style="font-weight: 600; margin-top: 6px;">${esc(c.city)}</p><div style="display: flex; flex-direction: column; gap: 12px; margin-top: 20px; font-size: 14px;"><p class="row" style="gap: 10px; font-weight: 700;"><span class="chip chip-coral" style="height: 26px;">${icon('calendar-days', 12)}${esc(schedule(petronas))}</span></p><p class="row" style="gap: 10px; flex-wrap: wrap;">${stars(c.rating)}<b>${c.rating.toFixed(1)}</b><span class="muted">(${fmtNum(c.reviewCount)} reviews)</span><span class="tag">${priceLabel(c.priceLevel)}</span></p><p class="row muted" style="gap: 10px; align-items: flex-start;">${icon('pin', 17)}<span>${esc(c.address)}</span></p><p class="row muted" style="gap: 10px;">${icon('clock', 17)}<span>${esc(c.openingHours)}</span></p></div><p style="font-size: 15px; line-height: 1.65; margin-top: 18px; padding-top: 18px; border-top: 1px solid var(--line);">${esc(c.description)}</p><p class="alert" style="margin-top: 16px; background: var(--coral-soft); color: var(--ink);"><span><b>Your note:</b> ${esc(petronas.notes)}</span></p><div class="row" style="justify-content: space-between; margin-top: 24px;"><h3 class="eyebrow">Reviews</h3><span class="faint" style="font-size: 11.5px;">Sample data for this prototype</span></div><ul style="list-style: none; margin: 12px 0 0; padding: 0; display: flex; flex-direction: column; gap: 10px;">${reviews}</ul></div><div class="row" style="gap: 10px; padding: 16px 36px; border-top: 1px solid var(--line); background: var(--raised);"><span class="btn btn-primary">${icon('external', 16)}Open in Google Maps</span><span class="btn btn-outline">${icon('pencil', 15)}Edit card</span></div></div></section>`;
  return screen(overlay(boardScreenDesktop(kl, { mode: 'edit', z: 0.8, tx: 36, ty: 250 }), modal), 900);
};

export const editCard = () => screen(overlay(boardScreenDesktop(kl, { mode: 'edit', selectedId: 'seed-kl-petronas-towers', z: 0.8, tx: 36, ty: 250 }), `<div class="modal" style="left: ${(W - 480) / 2}px; top: 140px; width: 480px;"><div class="modal-head"><div><h2 style="font-size: 22px;">Edit card</h2><p class="muted" style="font-size: 13px; margin-top: 2px;">${esc(petronas.c.name)}</p></div><span class="btn btn-ghost btn-icon" aria-label="Close">${icon('x', 18)}</span></div><div class="modal-body">${field('Custom label (optional)', input('e.g. Sunrise breakfast', { ph: true }))}<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px;">${field('Day', select('Day 2'))}${field('Start time', input('3:30 PM', { trail: icon('clock', 16) }))}</div>${field('Your note', `<div class="input area focus">${esc(petronas.notes)}</div>`, { help: 'Tickets, tips, who to meet…' })}</div><div class="modal-foot"><span class="btn btn-ghost">Cancel</span><span class="btn btn-primary">Save card</span></div></div>`), 900);

const shareShell = (tab, body) => `<div class="modal" style="left: ${(W - 540) / 2}px; top: 120px; width: 540px;"><div class="modal-head"><div><h2 style="font-size: 22px;">Share this plan</h2><p class="muted" style="font-size: 13px; margin-top: 2px;">KL City Lights</p></div><span class="btn btn-ghost btn-icon" aria-label="Close">${icon('x', 18)}</span></div><div style="padding: 16px 24px 0;"><div class="seg" style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));"><span class="seg-item${tab === 'link' ? ' on' : ''}" style="justify-content: center;">${icon('link', 16)}Share as link</span><span class="seg-item${tab === 'news' ? ' on' : ''}" style="justify-content: center;">${icon('newspaper', 16)}Share as news</span></div></div><div class="modal-body">${body}</div></div>`;
export const shareLink = () => screen(overlay(boardScreenDesktop(kl, { mode: 'edit', z: 0.8, tx: 36, ty: 250 }), shareShell('link', `<p class="muted" style="font-size: 14px; line-height: 1.55;">Anyone with the link can view this board read-only, with the route summary and a PDF download. No sign-in needed.</p><div class="row" style="gap: 8px;">${input('travelplanner.local/shared/k7Qm2xVb9T', { style: 'flex: 1; font-family: ui-monospace, Menlo, monospace; font-size: 12.5px; background: var(--sunken);' })}<label class="btn btn-primary cc mx" style="height: 44px;"><input type="checkbox"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path class="mp back" d="${P.COPY_BACK}"></path><path class="mp front" d="${P.COPY}"></path></svg><span>Copy</span></label></div><div class="row" style="justify-content: space-between;"><a href="#" class="row" style="gap: 6px; font-weight: 700; font-size: 13.5px;">Open preview${icon('external', 14)}</a><span class="btn btn-danger-ghost btn-sm">Revoke link</span></div>`)), 900);
const story = `Look guys, this is my plan for Kuala Lumpur (KL City Lights). Stops: ${orderPlaces(kl).map((p) => p.c.name).join(' → ')}.\n\nWould love to hear what you’d add or skip!`;
export const shareNews = () => screen(overlay(boardScreenDesktop(kl, { mode: 'edit', z: 0.8, tx: 36, ty: 250 }), shareShell('news', `<p class="muted" style="font-size: 14px; line-height: 1.55;">Post your plan as a story on the News page. Readers can open the read-only board and like it.</p>${field('Caption', input('My plan for KL City Lights'), { help: '26 / 120' })}${field('Story', `<div class="input area" style="min-height: 150px; white-space: pre-line;">${esc(story)}</div>`)}<div class="row" style="justify-content: flex-end;"><span class="btn btn-primary">${icon('newspaper', 16)}Publish to News</span></div>`)), 900);

export const sharedBoard = () => screen(boardScreenDesktop(kl, { mode: 'shared', z: 0.66, tx: 30, ty: 250 }), 900);
export const sharedUnavailable = () => screen(`<div class="dots-bg" style="height: 760px; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; gap: 16px;">${brandMark(56)}<h1 style="font-size: 40px; margin-top: 12px;">This plan isn’t available</h1><p class="muted" style="font-size: 16px; max-width: 440px;">The link may have been revoked, or it never existed. Ask the person who shared it for a fresh link.</p><span class="btn btn-primary btn-lg" style="margin-top: 12px;">Plan your own trip${icon('arrow-right', 18)}</span></div>`, 760);

// ---------- News ----------
const totalLikes = newsSeeds.reduce((sum, p) => sum + p.baseLikes, 0) + tripPost.baseLikes;
export const newsScreen = () => screen(`${appNav('news')}<main class="container" style="padding: 24px 0 96px;"><div class="row" style="justify-content: space-between; align-items: flex-end; gap: 48px;"><div style="max-width: 760px;"><p class="eyebrow row" style="gap: 8px; color: var(--coral-deep);">${icon('newspaper', 14)}What’s new in Malaysia</p><h1 class="h-page" style="margin-top: 12px;">Fresh cafés, reopened beaches and markets worth a detour.</h1><p class="muted" style="margin-top: 14px; font-size: 15.5px; max-width: 620px;">Short reads from our editorial desk and plans shared by travellers. Like a story to save it for your next board.</p></div><div class="card" style="padding: 16px 20px; border-radius: 20px; display: flex; align-items: center; gap: 12px; flex: none;"><span style="display: flex; width: 40px; height: 40px; border-radius: 14px; align-items: center; justify-content: center; background: var(--coral-soft); color: var(--coral-deep);">${icon('heart', 18)}</span><div><p style="font: 800 24px/1 var(--display);">${fmtNum(totalLikes)}</p><p class="muted" style="font-size: 12.5px; margin-top: 3px;">likes so far</p></div></div></div><div class="pills" style="margin-top: 32px;">${['All stories', 'Trip plan', 'Café', 'Restaurant', 'Attraction', 'Event'].map((l, i) => `<span class="pill${i === 0 ? ' on' : ''}">${l}</span>`).join('')}</div><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; margin-top: 28px; align-items: stretch;">${[newsCard(tripPost, { w: 394, mine: true }), ...newsSeeds.map((p) => newsCard(p, { w: 394 }))].join('')}</div></main>`, 1960);

export const newsPost = () => {
  const p = newsSeeds[0];
  return screen(`${appNav('news')}<main style="width: 760px; margin: 0 auto; padding: 20px 0 96px;"><span class="btn btn-ghost btn-sm" style="padding: 0 10px 0 4px;">${icon('arrow-left', 16)}All stories</span><div class="cover" style="height: 380px; border-radius: 28px; margin-top: 18px; box-shadow: var(--shadow-2);"><img src="${img(p.coverImage)}" alt=""></div><div class="row" style="gap: 10px; flex-wrap: wrap; margin-top: 28px;"><span class="tag">${newsCategoryLabels[p.category]}</span><span class="row faint" style="gap: 5px; font-size: 12.5px; font-weight: 600;">${icon('pin', 13)}${esc(p.city)}</span><span class="faint" style="font-size: 12.5px; font-weight: 600;">· ${fmtNewsDate(p.publishedAt)}</span><span class="faint" style="font-size: 12.5px; font-weight: 600;">· ${esc(p.author)}</span></div><h1 style="font-size: 44px; line-height: 1.08; margin-top: 16px;">${esc(p.title)}</h1><p class="muted" style="font-size: 19px; line-height: 1.6; margin-top: 18px;">${esc(p.excerpt)}</p><div class="row" style="gap: 10px; margin-top: 24px; padding-bottom: 28px; border-bottom: 1px solid var(--line);">${likeBtn(p.baseLikes, { size: 'md' })}<span class="btn btn-outline btn-sm" style="height: 40px;">${icon('share', 15)}Share</span></div><div style="display: flex; flex-direction: column; gap: 22px; margin-top: 28px; font-size: 17px; line-height: 1.75;">${p.body.map((para) => `<p>${esc(para)}</p>`).join('')}</div><div class="card row" style="justify-content: space-between; margin-top: 44px; padding: 18px 22px; border-radius: 20px;"><span class="muted" style="font-size: 15px;">Enjoyed this one?</span>${likeBtn(p.baseLikes, { size: 'md', interactive: false })}</div></main>`, 1640);
};
