// Mobile (390) screens: bottom tab bar, bottom sheets instead of modals, board panels as sheets.
import { doc, esc, icon, img, P, brand, brandMark, themeToggle, likeBtn, stars, field, input, select, avatar, fmtNum, fmtNewsDate, newsSeeds, popularPlaces, seedTrips, catalog, byId, boardFor, categoryLabels, newsCategoryLabels, regionCover, leg, transport, priceLabel, rating } from './lib.mjs';
import { boardCanvas, boardSidebar, summaryPanel, schedule } from './board.mjs';
import { tripCard, popularCard, newsCard, heroPins, dateRange, mobileTop, tabBar, mobileFab } from './cards.mjs';
import { tripPost } from './system.mjs';

const kl = boardFor('seed-kl-city-lights');
const penang = boardFor('seed-penang-heritage');
const petronas = kl.placeById.get('seed-kl-petronas-towers');
const MW = 390;

const mCss = `
.sheet{position:absolute;left:0;right:0;bottom:0;background:var(--raised);border-radius:28px 28px 0 0;box-shadow:0 -24px 60px -24px rgb(14 20 48 / .5);border:1px solid var(--line);border-bottom:0;overflow:hidden}
.grab{width:40px;height:5px;border-radius:99px;background:var(--line2);margin:10px auto 4px}
.m-h1{font-size:32px;line-height:1.08}
.feat .fi{transition:border-radius .28s var(--ease),background .2s ease,color .2s ease}
.feat:hover .fi{border-radius:999px;background:var(--coral-soft);color:var(--coral-deep)}
`;
const m = (body, h, opts = {}) => doc(body, { width: MW, height: h, css: mCss, ...opts });
const frame = (h, inner) => `<div style="position: relative; width: ${MW}px; height: ${h}px; overflow: hidden;">${inner}</div>`;
const sheet = (h, inner) => `<div class="sheet" style="height: ${h}px;"><div class="grab"></div>${inner}</div>`;
const sheetHead = (title, sub = '') => `<div class="row" style="justify-content: space-between; padding: 6px 20px 14px;"><div><h2 style="font-size: 22px;">${title}</h2>${sub ? `<p class="muted" style="font-size: 13px; margin-top: 2px;">${sub}</p>` : ''}</div><span class="btn btn-soft btn-icon btn-sm" aria-label="Close">${icon('x', 16)}</span></div>`;
const topWithAvatar = () => mobileTop({ right: `<div class="row" style="gap: 2px;">${themeToggle()}${avatar('Demo Traveler', 34)}</div>` });

// ---------- Entry ----------
export const mLanding = () => {
  const [batu, tower, alor] = ['kl-batu-caves', 'kl-petronas-towers', 'kl-jalan-alor'].map((id) => byId.get(id));
  const mini = (c) => `<div style="border-radius: 14px; overflow: hidden; background: var(--raised); border: 1px solid var(--line); box-shadow: var(--shadow-2);"><div class="cover" style="height: 62px;"><img src="${img(c.image)}" alt=""></div><p class="trunc" style="padding: 7px 8px 8px; font: 650 11.5px/1.2 var(--body);">${esc(c.name)}</p></div>`;
  const features = [['grid', 'Plan on a visual board'], ['route', 'Connect the dots'], ['pin', `${catalog.length} places, ready to drag`], ['compass', 'Place intel in one tap'], ['newspaper', 'News from the ground'], ['bookmark', 'Collections for later']];
  return m(`${mobileTop({ right: `<div class="row" style="gap: 2px;">${themeToggle()}<span class="btn btn-ghost btn-sm">Sign in</span></div>` })}
<section style="padding: 20px 16px 48px;"><span class="chip chip-raised" style="height: 28px; box-shadow: var(--shadow-1);">${icon('pin', 12, '', ' style="color: var(--coral-deep);"')}Made for trips across Malaysia</span><h1 style="font: 800 44px/1.04 var(--display); letter-spacing: -0.035em; margin-top: 20px;">Plan your trip like a <span style="position: relative; display: inline-block; color: var(--primary-ink);">flow<svg class="squiggle" viewBox="0 0 188 20" preserveAspectRatio="none" aria-hidden="true" style="position: absolute; left: -2%; bottom: -9px; width: 104%; height: 13px; overflow: visible;"><path d="${P.LINE}" style="fill: none; stroke: var(--coral); stroke-width: 5; stroke-linecap: round;"></path></svg></span>, not a spreadsheet.</h1><p class="muted" style="font-size: 16px; line-height: 1.6; margin-top: 22px;">Drag places onto a board, connect them into a route, and keep the whole plan on one calm canvas.</p><div style="display: flex; flex-direction: column; gap: 10px; margin-top: 26px;"><span class="btn btn-primary btn-lg btn-block">Start a board${icon('arrow-right', 18)}</span><span class="btn btn-outline btn-lg btn-block">Explore the demo</span></div>
<div class="card dots-bg" style="margin-top: 32px; padding: 16px; border-radius: 24px; box-shadow: var(--shadow-3);"><div class="row" style="justify-content: space-between;"><span class="chip chip-raised">KL City Lights</span><span class="faint" style="font-size: 11.5px; font-weight: 600;">3 places · 2 routes</span></div><div style="position: relative; height: 70px; margin-top: 8px;">${heroPins({ w: 324, h: 70, pts: [[52, 54], [162, 30], [272, 54]], scale: 1.15 })}</div><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px;">${[batu, tower, alor].map(mini).join('')}</div><div class="row" style="justify-content: space-around; margin-top: 12px; font: 600 11.5px/1 var(--body); color: var(--muted);"><span class="row" style="gap: 5px;">${icon('train', 13)}Train · ${leg(batu, tower, 'train').duration}</span><span class="row" style="gap: 5px;">${icon('footprints', 13)}Walk · ${leg(tower, alor, 'walk').duration}</span></div></div></section>
<section style="background: var(--raised); border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); padding: 44px 16px;"><h2 style="font-size: 30px;">Everything on the board</h2><p class="muted" style="margin-top: 10px; font-size: 15px;">Explore three sample boards without an account.</p><div style="display: flex; flex-direction: column; gap: 10px; margin-top: 24px;">${features.map(([ic, t]) => `<div class="feat row" style="gap: 14px; padding: 14px; border-radius: 18px; background: var(--surface); border: 1px solid var(--line);"><span class="fi" style="display: flex; width: 44px; height: 44px; border-radius: 14px; align-items: center; justify-content: center; background: var(--raised); color: var(--primary-ink); border: 1px solid var(--line); flex: none;">${icon(ic, 20)}</span><span style="font: 700 15.5px/1.3 var(--display);">${esc(t)}</span></div>`).join('')}</div></section>
<section style="padding: 44px 16px;"><h2 style="font-size: 30px;">A planning board, not a booking site</h2><p class="muted" style="margin-top: 12px; font-size: 15px; line-height: 1.6;">Decide where to go and how to get between places. Bookings stay with the airlines and hotels. Your boards stay private until you share them.</p><div style="margin-top: 22px; border-radius: 24px; padding: 20px; background: #1B2559; color: #EDF2FB;"><p style="font: 700 16px/1.3 var(--display);">Three demo boards included</p><div style="display: flex; flex-direction: column; gap: 8px; margin-top: 14px;">${seedTrips.map((t) => `<div class="row" style="gap: 12px; padding: 10px; border-radius: 14px; background: rgb(255 255 255 / 0.06);"><span class="cover" style="width: 52px; height: 38px; border-radius: 9px; flex: none;"><img src="${regionCover(t.region)}" alt=""></span><span style="font: 650 13.5px/1.3 var(--body);">${esc(t.destination)}</span></div>`).join('')}</div></div><span class="btn btn-primary btn-lg btn-block" style="margin-top: 22px;">Create account</span></section>
<footer style="padding: 24px 16px 36px; border-top: 1px solid var(--line); display: flex; flex-direction: column; gap: 10px;">${brand(24, true, 14)}<p class="faint" style="font-size: 12px; font-weight: 600;">© 2026 TravelPlanner · Plan the flow, enjoy the trip.</p></footer>`, 2080);
};

const mAuth = (title, sub, fields, cta, footer) => m(`${mobileTop()}<section style="padding: 28px 20px 40px;"><h1 class="m-h1">${title}</h1><p class="muted" style="margin-top: 10px; font-size: 15px;">${sub}</p><div style="display: flex; flex-direction: column; gap: 16px; margin-top: 28px;">${fields}</div><span class="btn btn-primary btn-lg btn-block" style="margin-top: 24px;">${cta}</span>${footer}</section>`, 844);
const orDemo = `<div class="row" style="gap: 12px; margin: 22px 0 6px;"><span style="flex: 1; height: 1px; background: var(--line);"></span><span class="faint" style="font-size: 12px; font-weight: 600;">or</span><span style="flex: 1; height: 1px; background: var(--line);"></span></div><span class="btn btn-outline btn-lg btn-block" style="color: var(--primary-ink);">Explore the demo boards</span>`;
export const mSignIn = () => mAuth('Sign in', 'Pick up your boards where you left them.', `${field('Email', input('demo@travelplanner.local', { lead: icon('mail', 16) }))}${field('Password', input('•••••••••••••••••', { lead: icon('lock', 16), trail: icon('eye', 16) }))}`, 'Sign in', `<div class="alert alert-info" style="margin-top: 14px; font-size: 12.5px;">${icon('user', 15)}<span>Demo: <b>demo@travelplanner.local</b> / TravelPlanner123!</span></div>${orDemo}<p class="muted" style="text-align: center; margin-top: 18px; font-size: 14px;">New here? <a href="#">Create an account</a></p>`);
export const mSignUp = () => mAuth('Create your account', 'Your account lives on this machine in the local prototype.', `${field('Full name', input('Aina Rahman'))}${field('Email', input('aina@', { cls: 'error', lead: icon('mail', 16) }), { req: true, error: 'Enter a full email address, like aina@example.com.' })}${field('Password', input('At least 8 characters', { ph: true, lead: icon('lock', 16), trail: icon('eye', 16) }), { req: true })}`, 'Create account', `${orDemo}<p class="muted" style="text-align: center; margin-top: 18px; font-size: 14px;">Already have an account? <a href="#">Sign in</a></p>`);

// ---------- Home ----------
const mStats = () => `<div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; margin-top: 18px;">${[['Upcoming', 3, 'var(--primary)'], ['Active', 0, 'var(--pos)'], ['Past', 0, 'var(--faint)']].map(([l, v, dot]) => `<div class="card" style="padding: 12px 14px; border-radius: 18px;"><p style="font: 800 26px/1 var(--display);">${v}</p><p class="row" style="gap: 6px; margin-top: 6px; font: 700 12px/1 var(--body); color: var(--muted);"><span style="width: 7px; height: 7px; border-radius: 9px; background: ${dot};"></span>${l}</p></div>`).join('')}</div>`;
const mDashboardBody = () => `${topWithAvatar()}<main style="padding: 8px 16px 120px;"><h1 class="m-h1">Hi Demo, your boards</h1><p class="muted" style="margin-top: 8px; font-size: 14.5px;">Everything you change is saved in this browser.</p><div style="margin-top: 16px;">${input('Search trips or regions', { ph: true, lead: icon('search', 16), style: 'border-radius: 999px; background: var(--raised);' })}</div>${mStats()}<div style="display: flex; flex-direction: column; gap: 16px; margin-top: 22px;">${seedTrips.map((t) => tripCard(t, { w: 358 })).join('')}</div><section style="margin: 28px -16px 0; padding: 22px 0 22px 16px; background: #1B2559; color: #EDF2FB;"><span class="chip" style="height: 26px; background: rgb(255 255 255 / 0.1); color: #EDF2FB;">${icon('sparkles', 12)}Popular right now</span><h2 style="font-size: 22px; margin-top: 12px; color: #FFFFFF; padding-right: 16px;">Places travellers are adding to their boards</h2><div style="display: flex; gap: 12px; margin-top: 16px;">${popularPlaces.slice(0, 3).map((c) => popularCard(c, { w: 210 })).join('')}</div></section></main>`;
export const mDashboard = () => m(frame(1900, `${mDashboardBody()}${mobileFab()}${tabBar('trips')}`), 1900);
export const mNewTrip = () => m(frame(844, `${mDashboardBody()}<div class="scrim"></div>${sheet(660, `${sheetHead('New Trip', 'The cover follows the region you pick.')}<div style="display: flex; flex-direction: column; gap: 14px; padding: 0 20px;"><div class="cover" style="height: 88px; border-radius: 16px;"><img src="${regionCover('Ipoh')}" alt=""></div>${field('Trip name', input('Ipoh long weekend', { cls: 'focus' }), { req: true })}${field('Region', select('Ipoh'))}<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px;">${field('Start', input('Dec 12, 2026'), { req: true })}${field('End', input('Dec 14, 2026'), { req: true })}</div>${field('Description (optional)', input('What’s the vibe of this trip?', { ph: true }))}<span class="btn btn-primary btn-lg btn-block" style="margin-top: 4px;">Create trip</span></div>`)}`), 844);

const collections = [
  { destination: 'Cameron Highlands', status: 'want_to_go', notes: 'Tea terraces and cold mornings after KL.' },
  { destination: 'Malacca', status: 'visited', notes: 'Jonker night market was the highlight.' },
];
const mCollectionItem = (item) => `<article style="padding: 12px; border-radius: 20px; background: var(--raised); border: 1px solid var(--line); display: flex; flex-direction: column; gap: 12px;"><div class="row" style="gap: 12px;"><span class="cover" style="width: 76px; height: 56px; border-radius: 12px; flex: none;"><img src="${regionCover(item.destination)}" alt=""></span><div style="min-width: 0; flex: 1;"><h4 style="font-size: 16px;">${esc(item.destination)}</h4><p class="muted" style="font-size: 13px; margin-top: 3px;">${esc(item.notes)}</p></div><span class="btn btn-ghost btn-icon btn-sm" aria-label="More actions for ${esc(item.destination)}">${icon('more', 18)}</span></div><div class="row" style="gap: 8px;"><span class="btn btn-primary btn-sm" style="flex: 1; height: 40px;">${icon('plus', 14)}Plan trip</span>${item.status === 'want_to_go' ? `<span class="btn btn-outline btn-sm" style="flex: 1; height: 40px;">${icon('check', 14)}Mark visited</span>` : `<span class="btn btn-outline btn-sm" style="flex: 1; height: 40px;">${icon('undo', 14)}Want to go</span>`}</div></article>`;
export const mCollections = () => m(frame(1080, `${topWithAvatar()}<main style="padding: 8px 16px 120px;"><h1 class="m-h1">Collections</h1><p class="muted" style="margin-top: 8px; font-size: 14.5px;">Save places you have visited or want to turn into boards.</p><div class="card" style="margin-top: 20px; padding: 16px; display: flex; flex-direction: column; gap: 12px;">${field('Destination', input('e.g. Ipoh', { ph: true }), { req: true })}${field('Notes', input('Why it’s on the list', { ph: true }))}<div style="display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; align-items: end;">${field('Status', select('Want to go'))}<span class="btn btn-primary" style="height: 44px;">${icon('plus', 16)}Save</span></div></div><div class="seg" style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); margin-top: 24px;"><span class="seg-item on" style="justify-content: center;">Want to go · 1</span><span class="seg-item" style="justify-content: center;">Visited · 1</span></div><div style="display: flex; flex-direction: column; gap: 10px; margin-top: 14px;">${collections.filter((c) => c.status === 'want_to_go').map(mCollectionItem).join('')}</div><p class="eyebrow" style="margin: 22px 0 10px;">Visited</p>${collections.filter((c) => c.status === 'visited').map(mCollectionItem).join('')}</main>${mobileFab()}${tabBar('collections')}`), 1080);

export const mProfile = () => m(frame(1320, `${mobileTop()}<main style="padding: 8px 16px 120px;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px; text-align: center; margin-top: 8px;">${avatar('Demo Traveler', 104)}<span class="btn btn-outline btn-sm">${icon('camera', 15)}Upload photo</span></div><div style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; margin-top: 22px;">${[['Boards', 3], ['Complete', 1], ['Liked', 0]].map(([l, v]) => `<div class="card" style="padding: 12px; border-radius: 18px; text-align: center;"><p style="font: 800 24px/1 var(--display);">${v}</p><p class="eyebrow" style="margin-top: 6px; font-size: 10px;">${l}</p></div>`).join('')}</div><div class="card" style="margin-top: 16px; padding: 18px; display: flex; flex-direction: column; gap: 16px;">${field('Display name', input('Demo Traveler'), { req: true })}${field('Email', input('demo@example.com', { cls: 'readonly' }), { help: 'Used to sign in' })}${field('Gender', select('Prefer not to say'))}${field('Date of birth', input('Not set', { ph: true, trail: icon('calendar', 16) }))}${field('Home city', input('Kuala Lumpur'))}${field('Country', input('Malaysia'))}${field('Short bio', `<div class="input area ph">Slow mornings, street food, one museum per trip.</div>`, { help: '0 / 280' })}<span class="btn btn-primary btn-lg btn-block">Save profile</span></div><span class="btn btn-danger-ghost btn-block" style="margin-top: 20px; height: 48px; border: 1px solid var(--line);">${icon('log-out', 16)}Sign out</span></main>${tabBar('profile')}`), 1320);

// ---------- Board ----------
const mBoardHead = (trip, mode = 'edit') => {
  const actions = {
    edit: `<span class="btn btn-ghost btn-icon btn-sm" aria-label="Share">${icon('share', 17)}</span><span class="btn btn-ghost btn-icon btn-sm" aria-label="More actions">${icon('more', 18)}</span><span class="btn btn-primary btn-sm">${icon('circle-check', 15)}Save</span>`,
    view: `<span class="btn btn-ghost btn-icon btn-sm" aria-label="Share">${icon('share', 17)}</span><span class="btn btn-outline btn-sm">${icon('pen-line', 14)}Edit</span>`,
    shared: `<span class="btn btn-ghost btn-icon btn-sm" aria-label="Download PDF">${icon('download', 17)}</span>${themeToggle()}`,
  }[mode];
  const lead = mode === 'shared' ? avatar('Demo Traveler', 34) : `<span class="btn btn-ghost btn-icon btn-sm" aria-label="Back to Dashboard">${icon('arrow-left', 18)}</span>`;
  const badge = mode === 'view' ? `<span class="chip chip-mist" style="height: 18px; font-size: 9.5px;">Viewing</span>` : mode === 'shared' ? `<span class="chip chip-mist" style="height: 18px; font-size: 9.5px;">Shared</span>` : '';
  return `<header class="bhead" style="height: 60px; padding: 0 10px 0 8px; gap: 8px;">${lead}<div style="min-width: 0; flex: 1;"><h1 class="row" style="gap: 6px; font-size: 16.5px;"><span class="trunc">${esc(trip.destination)}</span>${badge}</h1><p class="muted trunc" style="font-size: 11.5px; margin-top: 2px;">${mode === 'shared' ? 'by Demo Traveler · ' : ''}${esc(trip.region)} · ${dateRange(trip.start_date, trip.end_date)}</p></div>${actions}</header>`;
};
const mCanvas = (board, o = {}) => boardCanvas(board, { width: MW, height: 784, z: 0.58, tx: 14, ty: 150, compact: true, minimapOn: false, controlsOn: false, sidebarOpen: false, ...o });
const mBoard = (board, mode, canvasOpts, over = '') => m(frame(844, `${mBoardHead(board.trip, mode)}${mCanvas(board, { readOnly: mode !== 'edit', summaryBtn: mode !== 'edit', ...canvasOpts })}${over}`), 844);

export const mBoardEdit = () => mBoard(kl, 'edit', { selectedId: 'seed-kl-merdeka-square', ty: 140 }, sheet(360, `<div class="row" style="justify-content: space-between; padding: 2px 16px 0;"><p class="eyebrow">Places in Malaysia</p><span class="faint" style="font-size: 11.5px; font-weight: 600;">7 on board</span></div><div style="height: 330px; overflow: hidden;">${boardSidebar(kl, { width: MW, height: 420, rows: 4 }).replace('class="side"', 'class="side" data-sheet="1"').replace('<p class="eyebrow">Places in Malaysia</p>', '')}</div>`));
export const mBoardView = () => mBoard(penang, 'view', { tx: 10, ty: 100, z: 0.5 }, sheet(430, `<div style="height: 410px; overflow: hidden;">${summaryPanel(penang, { width: MW, height: 420, border: false, closeBtn: true })}</div>`));
export const mShared = () => mBoard(kl, 'shared', { tx: 14, ty: 150 }, sheet(150, `<div class="row" style="justify-content: space-between; padding: 6px 20px;"><div><p class="eyebrow row" style="gap: 6px;">${icon('list-ordered', 14)}Route summary</p><p class="muted" style="font-size: 13px; margin-top: 4px;">7 stops over 2 days · swipe up</p></div><span class="btn btn-primary btn-sm">Plan your own</span></div>`));

export const mPlaceIntel = () => {
  const c = petronas.c;
  return m(frame(844, `${mBoardHead(kl.trip)}${mCanvas(kl)}<div class="scrim"></div><div class="sheet" style="height: 800px; display: flex; flex-direction: column;"><div class="cover" style="position: relative; height: 210px; flex: none;"><img src="${img(c.image)}" alt="${esc(c.name)}"><div class="grab" style="position: absolute; left: 50%; top: 0; margin: 10px 0 0 -20px; background: rgb(255 255 255 / 0.7);"></div><span class="chip chip-raised" style="position: absolute; left: 16px; top: 24px;">${categoryLabels[c.category]}</span><span class="btn btn-icon btn-sm" style="position: absolute; right: 14px; top: 20px; background: rgb(14 20 48 / 0.55); color: #F5F8FE;" aria-label="Close place details">${icon('x', 16)}</span></div><div style="flex: 1; overflow: hidden; padding: 18px 20px 0;"><p class="eyebrow">Place intel · ${esc(c.region)}</p><h2 style="font-size: 28px; margin-top: 8px;">${esc(c.name)}</h2><div style="display: flex; flex-direction: column; gap: 10px; margin-top: 14px; font-size: 13.5px;"><span class="chip chip-coral" style="align-self: flex-start; height: 26px;">${icon('calendar-days', 12)}${esc(schedule(petronas))}</span><p class="row" style="gap: 8px; flex-wrap: wrap;">${stars(c.rating, 13)}<b>${c.rating.toFixed(1)}</b><span class="muted">(${fmtNum(c.reviewCount)})</span><span class="tag">${priceLabel(c.priceLevel)}</span></p><p class="row muted" style="gap: 8px;">${icon('clock', 16)}${esc(c.openingHours)}</p><p class="row muted" style="gap: 8px; align-items: flex-start;">${icon('pin', 16)}<span>${esc(c.address)}</span></p></div><p style="font-size: 14.5px; line-height: 1.6; margin-top: 14px; padding-top: 14px; border-top: 1px solid var(--line);">${esc(c.description)}</p><p class="alert" style="margin-top: 14px; background: var(--coral-soft); color: var(--ink);"><span><b>Your note:</b> ${esc(petronas.notes)}</span></p></div><div class="row" style="gap: 8px; padding: 12px 16px 26px; border-top: 1px solid var(--line);"><span class="btn btn-primary btn-lg" style="flex: 1;">${icon('external', 16)}Google Maps</span><span class="btn btn-outline btn-lg btn-icon" style="width: 52px;" aria-label="Edit card">${icon('pencil', 18)}</span></div></div>`), 844);
};

export const mEditCard = () => m(frame(844, `${mBoardHead(kl.trip)}${mCanvas(kl, { selectedId: 'seed-kl-merdeka-square', ty: 140 })}<div class="scrim"></div>${sheet(520, `${sheetHead('Edit card', esc(petronas.c.name))}<div style="display: flex; flex-direction: column; gap: 14px; padding: 0 20px;">${field('Custom label (optional)', input('e.g. Sunrise breakfast', { ph: true }))}<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px;">${field('Day', select('Day 2'))}${field('Start time', input('3:30 PM'))}</div>${field('Your note', `<div class="input area" style="min-height: 84px;">${esc(petronas.notes)}</div>`)}<div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin-top: 4px;"><span class="btn btn-outline btn-lg">Cancel</span><span class="btn btn-primary btn-lg">Save card</span></div></div>`)}`), 844);

export const mShare = () => m(frame(844, `${mBoardHead(kl.trip)}${mCanvas(kl)}<div class="scrim"></div>${sheet(470, `${sheetHead('Share this plan', 'KL City Lights')}<div style="display: flex; flex-direction: column; gap: 14px; padding: 0 20px;"><div class="seg" style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));"><span class="seg-item on" style="justify-content: center;">${icon('link', 15)}Link</span><span class="seg-item" style="justify-content: center;">${icon('newspaper', 15)}News</span></div><p class="muted" style="font-size: 13.5px; line-height: 1.55;">Anyone with the link can view this board read-only, with the route summary and a PDF.</p>${input('travelplanner.local/shared/k7Qm2xVb9T', { style: 'font-family: ui-monospace, Menlo, monospace; font-size: 12px; background: var(--sunken);' })}<label class="btn btn-primary btn-lg btn-block cc mx"><input type="checkbox"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path class="mp back" d="${P.COPY_BACK}"></path><path class="mp front" d="${P.COPY}"></path></svg>Copy link</label><div class="row" style="justify-content: space-between;"><a href="#" class="row" style="gap: 6px; font-weight: 700; font-size: 13.5px;">Open preview${icon('external', 14)}</a><span class="btn btn-danger-ghost btn-sm">Revoke link</span></div></div>`)}`), 844);

// ---------- News ----------
export const mNews = () => m(frame(2020, `${topWithAvatar()}<main style="padding: 8px 16px 120px;"><p class="eyebrow row" style="gap: 8px; color: var(--coral-deep);">${icon('newspaper', 14)}What’s new in Malaysia</p><h1 class="m-h1" style="margin-top: 10px;">Fresh cafés, reopened beaches and markets.</h1><p class="muted" style="margin-top: 10px; font-size: 14.5px;">Like a story to save it for your next board.</p><div style="display: flex; gap: 8px; margin: 18px -16px 0; padding: 0 16px; overflow: hidden;">${['All stories', 'Trip plan', 'Café', 'Restaurant', 'Attraction'].map((l, i) => `<span class="pill${i === 0 ? ' on' : ''}" style="flex: none;">${l}</span>`).join('')}</div><div style="display: flex; flex-direction: column; gap: 16px; margin-top: 18px;">${[newsCard(tripPost, { w: 358, mine: true }), ...newsSeeds.slice(0, 3).map((p) => newsCard(p, { w: 358 }))].join('')}</div></main>${tabBar('news')}`), 2020);
export const mNewsPost = () => {
  const p = newsSeeds[0];
  return m(frame(1700, `${mobileTop({ left: `<span class="btn btn-ghost btn-sm" style="padding: 0 10px 0 4px;">${icon('arrow-left', 16)}All stories</span>` })}<main style="padding: 4px 16px 120px;"><div class="cover" style="height: 200px; border-radius: 22px;"><img src="${img(p.coverImage)}" alt=""></div><div class="row" style="gap: 8px; flex-wrap: wrap; margin-top: 18px;"><span class="tag">${newsCategoryLabels[p.category]}</span><span class="row faint" style="gap: 5px; font-size: 12px; font-weight: 600;">${icon('pin', 12)}${esc(p.city)} · ${fmtNewsDate(p.publishedAt)}</span></div><h1 style="font-size: 30px; line-height: 1.12; margin-top: 12px;">${esc(p.title)}</h1><p class="muted" style="font-size: 16.5px; line-height: 1.6; margin-top: 12px;">${esc(p.excerpt)}</p><div class="row" style="gap: 8px; margin-top: 18px; padding-bottom: 20px; border-bottom: 1px solid var(--line);">${likeBtn(p.baseLikes, { size: 'md' })}<span class="btn btn-outline btn-icon" aria-label="Share">${icon('share', 16)}</span></div><div style="display: flex; flex-direction: column; gap: 18px; margin-top: 20px; font-size: 16px; line-height: 1.72;">${p.body.map((para) => `<p>${esc(para)}</p>`).join('')}</div><div class="card row" style="justify-content: space-between; margin-top: 32px; padding: 16px 18px; border-radius: 20px;"><span class="muted">Enjoyed this one?</span>${likeBtn(p.baseLikes, { size: 'md', interactive: false })}</div></main>${tabBar('news')}`), 1700);
};
